config/routes.rb
Rails.application.routes.draw do

  get 'home/about'
  root :to => 'home#top'

  devise_for :users
  root 'users#show'

  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'search' => 'searches#search'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user, optional: true
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }


	def self.search(search,word)
	    if search == "forward_match"
	      @book = Book.where("name LIKE?", "#{word}%")
	    elsif search == "backward_match"
	      @book = Book.where("name LIKE?", "%#{word}")
	    elsif search == "perfect_match"
	      @book = Book.where("#{word}")
	    elsif search == "partial_match"
	      @book = Book.where("name LIKE?", "%#{word}%")
	    else
	      @book = Book.all
	  	end
	end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

	belongs_to :user
	belongs_to :book
	validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def self.search(search,word)
    if search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "perfect_match"
      @user = User.where("#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



 before_action :configure_permitted_parameters, if: :devise_controller?

 	def after_sign_in_path_for(resource)
 		user_path(resource)
 	end
  private

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

	def create
		book = Book.find(params[:book_id])
		comment = current_user.book_comments.new(book_comment_params)
		comment.book_id = book.id
		comment.save
		redirect_to book_path(book)
	end

	def destroy
		BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
		redirect_to book_path(params[:book_id])
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :authenticate_user!
  def new
    @books = Book.all
  	@book = Book.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @book.user_id = current_user.id
  end

  def show
    @book_show = Book.find(params[:id])
    @book = Book.new
    @books = Book.all
    @book_comment = BookComment.new
  end

  def create
  	@book = Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
  	if @book.save
  	 redirect_to book_path(@book.id), notice: 'You have creatad book successfully.'
    else
      render :index
    end
  end

  def edit
    @books = Book.all
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'You have updated book successfully.'
    else
      render :edit
    end

  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
		favorite.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: book.id)
		favorite.destroy
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 
  def top
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def follower
    user = User.find(params[:user_id])
    @users = user.following_user
  end

  def followed
    user = User.find(params[:user_id])
    @users = user.follower_user
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def search
		@range = params[:range]
		search = params[:search]
		word = params[:word]

		if @range == '1'
			@user = User.search(search,word)
		else
			@book = Book.search(search,word)
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!

  def show
  	@user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

  def follows

  end

  def followers
    
  end

  def new
    @user = User.new
  end

  def index
  	@users = User.all
    @book = Book.new
  end

  def create
  	@user = User.new(user_params)
  	@user.save
  	redirect_to users_path
  end



  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<td>
  <%= link_to user_path(book.user) do %>
    <%= attachment_image_tag book.user, :profile_image, size: '40x40', fallback: "no_image.jpg" %>
  <% end %>
</td>
<td><%= link_to book.title, book_path(book.id) %></td>
<td><%= book.body %></td>
<td>
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete do %>
      <span class="glyphicon glyphicon-heart"><%= book.favorites.count %></span>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post do %>
    <span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></span>
    <% end %>
  <% end %>
</td>
<td><p>コメント数:<%= book.book_comments.count %></p></td>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>

  <div class="field row">
    <label class="book_title">Title</label>
    <%= f.text_field :title, class: "col-xs-12" %>
  </div>

  <div class="field row">
    <label class="book_opinion">Opinion</label>
    <%= f.text_area :body, class: "col-xs-12" %>
  </div>
  <br>

  <div class="actions row">
    <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <%= render '/books/book', book: book %>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
  <p id="notice"></p>


  <div class="row">
	   <div class="col-md-6 col-md-offset-3">

        <% if @book.errors.any? %>
          <div id="error_explanation" style="color: red;">
              <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
		    <h1>Editing Book</h1>

      		<%= form_for(@book) do |f| %>
            <div class="field row">
              <label for="book_title">Title</label>
              <%= f.text_field :title, class: "col-xs-12 book_title" %>
            </div>

            <div class="field row">
              <label for="book_opinion">Opinion</label>
              <%= f.text_area :body, class: "col-xs-12 book_body" %>
            </div><br>

            <div class="actions row">
              <%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %>
            </div>
          <% end %>
		      <%= link_to "Show", book_path %> |
		      <%= link_to "Back", books_path %>
    </div>
  </div>

</div>

app/views/books/index.html.erb
<body>
  <div class="container">
    <p id="notice"></p>

<%= render 'layouts/errors', obj: @book %>

<div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <%= render 'users/info', user: current_user %>


    <h2>New book</h2>
    <%= render 'form', book: @book %>
  </div>

  <div class="col-xs-9">
    <h2>Books</h2>
    <%= render 'index', books: @books %>
  </div>
</div>

</body>

app/views/books/new.html.erb
<body>
    <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="glyphicon glyphicon-home home">
           <%= link_to "Home", user_path(current_user.id) %>
          </li>
          <li class="glyphicon glyphicon-user users"> <%= link_to "Users", user_path(current_user.id) %>
          </li>
          <li class="glyphicon glyphicon-book books"> <%= link_to "Books", books_path %>
          </li>
          <li class="glyphicon glyphicon-log-out logout">
           <%= link_to "logout", destroy_user_session_path, method: :delete %>
           </li>

        <% else %>
          <li class="glyphicon glyphicon-home home">
            <%= link_to "Home", root_path %>
          </li>
          <li class="glyphicon glyphicon-link about">  <%= link_to "About", new_book_path %>
          </li>
          <li class="glyphicon glyphicon-edit sign_up">
            <%= link_to "sign up", new_user_registration_path %>
          </li>
          <li class="glyphicon glyphicon-log-in sign_in">
            <%= link_to "login", user_session_path %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

<div class="body">
  <div class="container">
    <p id="notice"></p>
      <div class="row">
  
        <div class="col-xs-3">
          <h2>User info</h2>
          <img class="attachment user profile_image fallback" src="/assets/no_image-ede28af4bad96368ef41be1b4be1cffce0d9402540f75d17895e32cb0d2af5e6.jpg" alt="No image">

          <table class="table">
            <tbody>
              <tr></tr> 

              <tr>
                <th>name</th>
                <th><%= current_user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th></th>
              </tr>
            </tbody>
          </table>

          <div class="row">
            <a class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_22936" href="/users/22936/edit"></a>
          </div>

          <h2>New book</h2>
            <%= form_for(@book) do |f| %>
              <div class="field row">
                <label for="book_title">Title</label>
                <input class="col-xs-12 book_title" type="text" name="book[title]" id="book_title">
              </div>

              <div class="field row">
                <label for="book_opinion">Opinion</label>
                <textarea class="col-xs-12 book_body" name="book[body]" id="book_body"></textarea>
              </div>

              <input type="submit" name="commit" value="Create Book" class="btn btn-primary col-xs-12" data-disable-with="Create Book">
            <% end %>

        </div>

        <div class="col-xs-9">
          <h2>Books</h2>

          <table class="table">
              <thead>
                <tr> 
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @books.each do |book| %>
                  <tr>
                    <td></td>
                    <td><%= book.title %></td>
                    <td><%= book.body %></td>
                  </tr>
                <% end %>
              </tbody>
          </table>
        </div>
      </div>
    </div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

</body>

app/views/books/show.html.erb
<body>
  <div class="container">
    <p id="notice">
      <%= notice %>
    </p>
    <div class="row">
      
      <div class="col-xs-3">
        <h2>User info</h2>
        <img class="attachment user profile_image fallback">
        <table class="table">
          <tbody>
            <tr><%= attachment_image_tag @book_show.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %></tr> 
            <tr>
              <th>name</th>
              <th><%= @book_show.user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @book_show.user.introduction %></th>
            </tr>
          </tbody>
        </table>

        <div class="row">
          <%= link_to edit_user_path(current_user) do %><i class="col-xs-12 btn btn-default glyphicon glyphicon-wrench"></i><% end %>
        </div>

        <div class="row">
          <h2>New book</h2>
          <%= form_for(@book) do |f| %>
            <div class="field row">
              <label class="book_title">Title</label>
              <%= f.text_field :title, class: "col-xs-12" %>
            </div>

            <div class="field row">
              <label class="book_opinion">Opinion</label>
              <%= f.text_area :body, class: "col-xs-12" %>
            </div>
            <br>

            <div class="actions row">
              <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
            </div>
          <% end %>
        </div>

      </div>

      <div class="col-xs-9">
        <h2>Book detail</h2>

        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <tbody>

              <tr>
                <td>
                  <%= link_to user_path(@book_show.user) do %>
                    <%= attachment_image_tag @book_show.user, :profile_image, size: '40x40', fallback: "no_image.jpg" %><br>
                    <%= @book_show.user.name %>
                  <% end %>
                </td>
                <td><%= @book_show.title %></td>
                <td><%= @book_show.body %></td>
                <td><% if @book_show.favorited_by?(current_user) %>
                        <%= link_to book_favorites_path(@book_show), method: :delete do %>
                          <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                          <%= @book_show.favorites.count %>
                        <% end %>
                      <% else %>
                        <%= link_to book_favorites_path(@book_show), method: :post do %>
                          <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                          <%= @book_show.favorites.count %>
                        <% end %>
                    <% end %></td>
                <td><p>コメント数:<%= @book_show.book_comments.count %></p></td>
                  <td>
                    <% if @book_show.user == current_user %>
                      <%= link_to 'Edit', edit_book_path, class: "btn-sm btn-success" %>
                  <% end %>
                  </td>

                  <td>
                    <% if @book_show.user == current_user %>
                      <%= link_to 'Destroy', book_path, method: :delete, data: { confirm: '本当に消しますか?' }, class: "btn-sm btn-danger" %>
                    <% end %>
                  </td>
              </tr>

          </tbody>
        </table>

        <table>
          <% @book_show.book_comments.each do |book_comment| %>
            <tr>
            <td class="show-comment">
                <%= link_to user_path(book_comment.user), class: "user_#{book_comment.user.id}" do %>
                  <%= attachment_image_tag book_comment.user, :profile_image, fallback: "no_image.jpg", size: "50x50" %><br>
                  <%= book_comment.user.name %>
                <% end %>
            </td>
            <td class="comment-entry"><%= book_comment.comment %></td>
            <% if book_comment.user == current_user %>
              <td>
                <%= link_to "destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>)
                  </td>
            <% end %>
          </tr>
          <% end %>

      <div class="comment-form">
        <%= form_for [@book_show, @book_comment] do |f| %>
          <%= f.text_area :comment, size:'90x5' %>
          <%= f.submit "送信", class: "btn-sm btn-primary" %>
        <% end %>
      </div>
      
  </div>

</body>

app/views/books/top.html.erb
<body>

  <div class="container">

    <div class="row">
      <div class="top-message col-md-offset-3 col-lg-6">
        <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
        <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>

        <div class="btn-wrapper">
          <div class="row">
             <%= link_to new_user_session_path do %><i class="btn btn-info col-xs-10 col-xs-offset-1 sign_in">Log in</i><% end %>
          </div>
          <div class="row">
            <%= link_to new_user_registration_path do %><i class="btn btn-success col-xs-10 col-xs-offset-1 sign_up">Sign Up</i><% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete do %>
      <span class="glyphicon glyphicon-heart">
        <%= book.favorites.count %></span>
    <% end %>
<% else %>
    <%= link_to book_favorites_path(book), method: :post do %>
      <span class="glyphicon glyphicon-heart-empty">
        <%= book.favorites.count %></span>
    <% end %>
<% end %>


app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr> 
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, size: '40x40', fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user.id), class:"edit_#{user.id}" %></td>
        <td>フォロー数：<%= user.follower.count %></td>
        <td>フォロワー数：<%= user.followed.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class="table">
  <tbody>
    <tr><%= attachment_image_tag current_user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %></tr> 

    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

<div class="row">
  <%= link_to '' ,edit_user_path(user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<body>
  <div class="container">
    <p id="notice"></p>
    <h2>User info</h2>
    <% if @user.errors.any? %>
      <div id="error_explanation" style="color: red;">
          <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
      <%= form_for(@user) do |f| %>
        <div class="field">
          <label for="user_name">Name</label>
          <%= f.text_field :name %>
        </div><br>

        <div class="field">
          <label for="user_image">Image</label>
          <%= f.attachment_field :profile_image, class: "user_edit_form" %>
          <br>
        </div>

        <div class="field">
          <label for="user_introduction">Introduction</label>
              <%= f.text_area :introduction %>
              <br>
        </div>

        <div class="actions">
          <%= f.submit "Update User" %>
        </div>
      <% end %>

  </div>
</body>

app/views/users/index.html.erb
<body>

<div class="body">
  <div class="container">
    <p id="notice"></p>
      <div class="row">
  
        <div class="col-xs-3">
          <h2>User info</h2>
            <%= render 'users/info', user: current_user %>

          <h2>New book</h2>
            <%= render 'books/form', book: @book %>
        </div>

        <div class="col-xs-9">
          <h2>Users</h2>
            <%= render 'index', users:@users  %>
        </div>

      </div>
    </div>

</body>

app/views/users/show.html.erb
<body>
  <div class="container col.lg-8">

    <%= render 'layouts/notifications' %>

      <div class="row">

        <div class="col-xs-3">
          <h2>User info</h2>
          <%= render 'users/info', user:current_user %>

          <h2>New book</h2>
          <%= render 'books/form', book: @book %>
        </div>

        <div class="col-xs-9">
          <h2>Books</h2>
          <%= render 'books/index', books: @books %>
        </div>
      </div>
  </div>
</body>