config/routes.rb
Rails.application.routes.draw do

  get 'home/about'
  root :to => 'home#top'

  devise_for :users
  root 'users#show'

  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'search' => 'searches#search'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user, optional: true
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }


	def self.search(search,word)
	    if search == "forward_match"
	      @book = Book.where("name LIKE?", "#{word}%")
	    elsif search == "backward_match"
	      @book = Book.where("name LIKE?", "%#{word}")
	    elsif search == "perfect_match"
	      @book = Book.where("#{word}")
	    elsif search == "partial_match"
	      @book = Book.where("name LIKE?", "%#{word}%")
	    else
	      @book = Book.all
	  	end
	end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

	belongs_to :user
	belongs_to :book
	validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def self.search(search,word)
    if search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "perfect_match"
      @user = User.where("#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :authenticate_user!
  def new
    @books = Book.all
  	@book = Book.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @book.user_id = current_user.id
  end

  def show
    @book_show = Book.find(params[:id])
    @book = Book.new
    @books = Book.all
    @book_comment = BookComment.new
  end

  def create
  	@book = Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
  	if @book.save
  	 redirect_to book_path(@book.id), notice: 'You have creatad book successfully.'
    else
      render :index
    end
  end

  def edit
    @books = Book.all
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'You have updated book successfully.'
    else
      render :edit
    end

  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
		favorite.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: book.id)
		favorite.destroy
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 
  def top
  end
  
  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def search
		@range = params[:range]
		search = params[:search]
		word = params[:word]

		if @range == '1'
			@user = User.search(search,word)
		else
			@book = Book.search(search,word)
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!

  def show
  	@user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

  def follows

  end

  def followers
    
  end

  def new
    @user = User.new
  end

  def index
  	@users = User.all
    @book = Book.new
  end

  def create
  	@user = User.new(user_params)
  	@user.save
  	redirect_to users_path
  end



  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation" style="color: red;">
    <h3><%= obj.errors.count %>errors prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_notifications.html.erb


<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "flash flash__#{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>


  <header>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
        <p class="nav navbar-nav navbar-left" style="font-size: 20px; color: white;">Bookers</p>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to user_path(current_user.id) do %><i class="glyphicon glyphicon-home"></i>　Home<% end %></li>

            <li><%= link_to users_path do %><i class="glyphicon glyphicon-user users"></i>　Users<% end %></li>
            <li><%= link_to books_path do %><i class="glyphicon glyphicon-book books"></i>　Books<% end %></li>
            <li><%= link_to destroy_user_session_path, method: :delete do %><i class="glyphicon glyphicon-log-out logout"></i>　logout<% end %></li>
          <% else %>
            <li><%= link_to root_path do %><i class="glyphicon glyphicon-home"></i>　Home<% end %></li>
            <li><%= link_to home_about_path do %><i class="glyphicon glyphicon-link about"></i>　About<% end %></li>
            <li><%= link_to new_user_registration_path do %><i class="glyphicon glyphicon-edit sign_up"></i>　sign up<% end %></li>
            <li><%= link_to new_user_session_path do %><i class="glyphicon glyphicon-log-in sign_in"></i>　login<% end %></li>
          <% end %>
        </ul>
       </div>
      </nav>
    </header>


  <div class="container">

    <% if user_signed_in? %>

      <%= form_tag(search_path, method: :get) do %>

      <%= select_tag 'range', options_for_select([['---選択してください---', ''], ['User', '1'], ['Book', '2']]) %>
        <%= select_tag 'search', options_for_select([["前方一致", "forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
        <%= text_field_tag (:word) %>
        <%= submit_tag "検索" %>
        <% end %>
    <% end %>

  </div>
  

    <%= yield %>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>